title: Jekyll & Egg 
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A kool website with jekyll and eggcss
baseurl: "" # the subpath of your site, e.g. /blog
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
